feat: Add EntityBase & Curve Implementation
- Updated `IDGenerator` to use DE pointers instead of PD pointers for ID reservation.
- Added `EntityBase` class to serve as the base class for all entities, providing methods for managing directory entry records.
- Implemented `NullEntity` class as a specific entity type with no parameters.
- Introduced the `UnsupportedEntity` class to represent entities not supported by the library.
- Added factory methods to create entities
  - returning `NullEntity` for `EntityType::kNull`
  - returning `UnsupportedEntity` for unsupported types.
- Developed unit tests for `EntityBase` and `UnsupportedEntity` to ensure correct functionality and reference handling.

fix: Resolve debug errors introduced in previous commit

- `factory.cpp:15:10: fatal error: 'igesio/entities/curves/circular_arc.h' file not found`
- `factory.cpp:15:10: fatal error: igesio/entities/curves/circular_arc.h: No such file or directory`

docs: Add documentation for entity classes and interfaces in IGES files

- Created en/ja documentation for entity interfaces and classes in `entities.md`/`entities_ja.md`.
- Introduced a comprehensive overview of the entity base class architecture in `entity_base_class_architecture.md`/`entity_base_class_architecture_ja.md`.
- Updated the README files to include links to the new documentation.

feat: Add ICurve interface and CircularArc entity implementation

- Introduced `ICurve` interface defining essential methods for curve entities.
- Implemented `ICurve2D` and `ICurve3D` as derived classes for 2D and 3D curves.
- Created `CircularArc` class to represent circular arc entity (type 100), including constructors for various initialization methods.
- Developed unit tests for CircularArc to verify functionality and correctness.